### ISSUE TITLE
Demo or paper?

### ISSUE THREAD

**Issue by francqz31** [seongq/flowmse#1]
Hey there , I'm sorry if I found this repo super early. But would there be a demo or a paper down the line? 
Is this better than sgmse or storm? idk I have a feeling that might end up as a SOTA , that's why I'm interested in this.

**Comment by seongq** [comment]
Thank you for your interest.

I have been training speech enhancement models with various flow settings, recently. However, I did not obtain better results than SGMSE or STORM. When I get better results than those, I will upload a demo and prepare a paper.
